<?php

declare(strict_types=1);

namespace App\Domain\Nutrition\ValueObject;

use Symfony\Component\Uid\Uuid;

/**
 * Value Object representing a unique identifier for a Restriction Entity generated by UUid.
 */
final class RestrictionId
{
    private Uuid $value;

    /**
     * @throws \InvalidArgumentException When UUID format is invalid
     */
    public function __construct(string $value)
    {
        if (!Uuid::isValid($value)) {
            throw new \InvalidArgumentException('Invalid UUid:'.$value);
        }
        $this->value = Uuid::fromString($value);
    }

    /**
     * Return the UUid as a string.
     *
     * @return string of UUid
     */
    public function getValue(): string
    {
        return $this->value->toString();
    }

    /**
     * Return a new self object with a generated UUid.
     *
     * @return self with a UUid generated
     */
    public static function generate(): self
    {
        return new self(Uuid::v6()->toString());
    }

    /**
     * Verify if two entites are equals.
     *
     * @return bool with the result of the compared string
     */
    public function equals(self $other): bool
    {
        return $this->getValue() === $other->getValue();
    }

    public function __toString(): string
    {
        return $this->value->toString();
    }
}
